using System.Collections.Immutable;
using Martin.Compiler.Text;
using Martin.Compiler.Diagnostics;
namespace Martin.Compiler.Syntax;

public sealed class SyntaxTrivia { public SyntaxTrivia(SyntaxKind kind, int position, string text) { Kind = kind; Position = position; Text = text; } public SyntaxKind Kind { get; } public int Position { get; } public string Text { get; } public TextSpan Span => new(Position, Text.Length); }
public abstract class SyntaxNode { public abstract SyntaxKind Kind { get; } public SyntaxNode? Parent { get; private set; } protected void AttachChildren(IEnumerable<SyntaxNode> children) { foreach (var child in children) child.Parent = this; } public virtual TextSpan Span { get { var c = GetChildren().ToArray(); if (c.Length == 0) return new(0, 0); return TextSpan.FromBounds(c.First().Span.Start, c.Last().Span.End); } } public virtual TextSpan FullSpan { get { var c = GetChildren().ToArray(); if (c.Length == 0) return Span; return TextSpan.FromBounds(c.First().FullSpan.Start, c.Last().FullSpan.End); } } public abstract IEnumerable<SyntaxNode> GetChildren(); public virtual string ToFullString() => string.Concat(GetChildren().Select(c => c.ToFullString())); public virtual void Accept(SyntaxVisitor visitor) => visitor.DefaultVisit(this); public virtual TResult Accept<TResult>(SyntaxVisitor<TResult> visitor) => visitor.DefaultVisit(this); public override string ToString() => ToFullString(); }
public sealed class SyntaxToken : SyntaxNode { public SyntaxToken(SyntaxKind kind, int position, string text, object? value = null, bool isMissing = false, IReadOnlyList<SyntaxTrivia>? leadingTrivia = null, IReadOnlyList<SyntaxTrivia>? trailingTrivia = null) { Kind = kind; Position = position; Text = text; Value = value; IsMissing = isMissing; LeadingTrivia = leadingTrivia ?? Array.Empty<SyntaxTrivia>(); TrailingTrivia = trailingTrivia ?? Array.Empty<SyntaxTrivia>(); } public override SyntaxKind Kind { get; } public int Position { get; } public string Text { get; } public object? Value { get; } public bool IsMissing { get; } public IReadOnlyList<SyntaxTrivia> LeadingTrivia { get; } public IReadOnlyList<SyntaxTrivia> TrailingTrivia { get; } public TextLocation Location(SourceText text) => new(text, Span); public override TextSpan Span => new(Position, Text.Length); public override TextSpan FullSpan { get { var start = LeadingTrivia.Count > 0 ? LeadingTrivia[0].Position : Position; var end = TrailingTrivia.Count > 0 ? TrailingTrivia[^1].Span.End : Span.End; return TextSpan.FromBounds(start, end); } } public override IEnumerable<SyntaxNode> GetChildren() { yield break; } public override string ToFullString() => string.Concat(LeadingTrivia.Select(t => t.Text)) + Text + string.Concat(TrailingTrivia.Select(t => t.Text)); }
public abstract class MemberSyntax : SyntaxNode { }
public abstract class StatementSyntax : SyntaxNode { }
public abstract class ExpressionSyntax : SyntaxNode { }
public sealed class CompilationUnitSyntax(IReadOnlyList<MemberSyntax> members, SyntaxToken eof) : SyntaxNode { public IReadOnlyList<MemberSyntax> Members { get; } = members; public SyntaxToken EndOfFileToken { get; } = eof; public override SyntaxKind Kind => SyntaxKind.CompilationUnit; public override IEnumerable<SyntaxNode> GetChildren() => Members.Cast<SyntaxNode>().Append(EndOfFileToken); }
public sealed class GlobalStatementSyntax(StatementSyntax statement) : MemberSyntax { public StatementSyntax Statement { get; } = statement; public override SyntaxKind Kind => SyntaxKind.GlobalStatement; public override IEnumerable<SyntaxNode> GetChildren() { yield return Statement; } }
public sealed class SyntaxTree { private SyntaxTree(SourceText text, CompilationUnitSyntax root, ImmutableArray<Diagnostic> diagnostics) { Text = text; Root = root; Diagnostics = diagnostics; } public SourceText Text { get; } public CompilationUnitSyntax Root { get; } public ImmutableArray<Diagnostic> Diagnostics { get; } public static SyntaxTree Parse(string text, string? filePath = null, CancellationToken cancellationToken = default) => Parse(SourceText.From(text, filePath), cancellationToken); public static SyntaxTree Parse(SourceText text, CancellationToken cancellationToken = default) { cancellationToken.ThrowIfCancellationRequested(); var p = new Parser(text, cancellationToken); var root = p.ParseCompilationUnit(); cancellationToken.ThrowIfCancellationRequested(); return new(text, root, p.Diagnostics.ToImmutableArray()); } }
public static class SyntaxTreePrinter { public static void WriteTo(SyntaxNode node, TextWriter writer, bool includeTrivia = false) => writer.Write(ToDisplayString(node, includeTrivia)); public static string ToDisplayString(SyntaxNode node, bool includeTrivia = false) { using var w = new StringWriter(); Pretty(w, node, "", true, includeTrivia); return w.ToString(); } static void Pretty(TextWriter w, SyntaxNode n, string indent, bool last, bool trivia) { w.Write(indent); w.Write(last ? "└── " : "├── "); w.Write(n.Kind); if (n is SyntaxToken t) { if (t.IsMissing) w.Write(" <missing>"); if (!string.IsNullOrEmpty(t.Text)) w.Write($" \"{t.Text}\""); if (t.Value != null) w.Write($" Value={t.Value}"); } w.WriteLine(); indent += last ? "    " : "│   "; var ch = n.GetChildren().ToArray(); for (int i = 0; i < ch.Length; i++) Pretty(w, ch[i], indent, i == ch.Length - 1, trivia); } }
