namespace Martin.Compiler.Syntax;
public enum SyntaxKind{BadToken,EndOfFileToken,IdentifierToken,IntegerLiteralToken,FloatingPointLiteralToken,StringLiteralToken,PlusToken,MinusToken,StarToken,SlashToken,PercentToken,BangToken,AmpersandAmpersandToken,PipePipeToken,EqualToken,EqualEqualToken,BangEqualToken,LessToken,LessOrEqualToken,GreaterToken,GreaterOrEqualToken,ArrowToken,OpenParenthesisToken,CloseParenthesisToken,OpenBraceToken,CloseBraceToken,OpenBracketToken,CloseBracketToken,ColonToken,CommaToken,DotToken,SemicolonToken,QuestionToken,LetKeyword,VarKeyword,FuncKeyword,IfKeyword,ElseKeyword,WhileKeyword,ReturnKeyword,TrueKeyword,FalseKeyword,NilKeyword,StructKeyword,ClassKeyword,InitKeyword,SelfKeyword,MutatingKeyword,EnumKeyword,CaseKeyword,SwitchKeyword,DefaultKeyword,ThrowsKeyword,ThrowKeyword,TryKeyword,DoKeyword,CatchKeyword,ProtocolKeyword,StaticKeyword,WhitespaceTrivia,LineBreakTrivia,SingleLineCommentTrivia,MultiLineCommentTrivia,DocumentationCommentTrivia,SkippedTextTrivia,CompilationUnit,GlobalStatement,FunctionDeclaration,Parameter,ParameterList,TypeClause,ReturnTypeClause,BlockStatement,VariableDeclarationStatement,ExpressionStatement,IfStatement,ElseClause,WhileStatement,ReturnStatement,AssignmentExpression,BinaryExpression,UnaryExpression,LiteralExpression,IdentifierExpression,ParenthesizedExpression,CallExpression,Argument,ArgumentList,StructDeclaration,ClassDeclaration,PropertyDeclaration,MethodDeclaration,InitializerDeclaration,MemberAccessExpression,ObjectCreationExpression,PropertyAssignmentExpression,OptionalType,IfLetStatement,EnumDeclaration,EnumCaseDeclaration,SwitchStatement,SwitchCase,WildcardPattern,IdentifierPattern,LiteralPattern,EnumCasePattern,OptionalSomePattern,ValueBindingPattern,NilPattern,PatternArgumentList,ProtocolDeclaration,ProtocolMethodRequirement,ProtocolPropertyRequirement,ProtocolConformanceClause,TypeParameterList,TypeParameter,TypeArgumentList,GenericName,ThrowsClause,ThrowStatement,TryExpression,DoCatchStatement,CatchClause}
public static class SyntaxFacts
{
 public static string? GetText(SyntaxKind k)=>k switch{SyntaxKind.PlusToken=>"+",SyntaxKind.MinusToken=>"-",SyntaxKind.StarToken=>"*",SyntaxKind.SlashToken=>"/",SyntaxKind.PercentToken=>"%",SyntaxKind.BangToken=>"!",SyntaxKind.AmpersandAmpersandToken=>"&&",SyntaxKind.PipePipeToken=>"||",SyntaxKind.EqualToken=>"=",SyntaxKind.EqualEqualToken=>"==",SyntaxKind.BangEqualToken=>"!=",SyntaxKind.LessToken=>"<",SyntaxKind.LessOrEqualToken=>"<=",SyntaxKind.GreaterToken=>">",SyntaxKind.GreaterOrEqualToken=>">=",SyntaxKind.ArrowToken=>"->",SyntaxKind.OpenParenthesisToken=>"(",SyntaxKind.CloseParenthesisToken=>")",SyntaxKind.OpenBraceToken=>"{",SyntaxKind.CloseBraceToken=>"}",SyntaxKind.OpenBracketToken=>"[",SyntaxKind.CloseBracketToken=>"]",SyntaxKind.ColonToken=>":",SyntaxKind.CommaToken=>",",SyntaxKind.DotToken=>".",SyntaxKind.SemicolonToken=>";",SyntaxKind.QuestionToken=>"?",SyntaxKind.LetKeyword=>"let",SyntaxKind.VarKeyword=>"var",SyntaxKind.FuncKeyword=>"func",SyntaxKind.IfKeyword=>"if",SyntaxKind.ElseKeyword=>"else",SyntaxKind.WhileKeyword=>"while",SyntaxKind.ReturnKeyword=>"return",SyntaxKind.TrueKeyword=>"true",SyntaxKind.FalseKeyword=>"false",SyntaxKind.NilKeyword=>"nil",SyntaxKind.StructKeyword=>"struct",SyntaxKind.ClassKeyword=>"class",SyntaxKind.InitKeyword=>"init",SyntaxKind.SelfKeyword=>"self",SyntaxKind.MutatingKeyword=>"mutating",SyntaxKind.EnumKeyword=>"enum",SyntaxKind.CaseKeyword=>"case",SyntaxKind.SwitchKeyword=>"switch",SyntaxKind.DefaultKeyword=>"default",SyntaxKind.ThrowsKeyword=>"throws",SyntaxKind.ThrowKeyword=>"throw",SyntaxKind.TryKeyword=>"try",SyntaxKind.DoKeyword=>"do",SyntaxKind.CatchKeyword=>"catch",SyntaxKind.ProtocolKeyword=>"protocol",SyntaxKind.StaticKeyword=>"static",_=>null};
 public static SyntaxKind GetKeywordKind(string t)=>t switch{"let"=>SyntaxKind.LetKeyword,"var"=>SyntaxKind.VarKeyword,"func"=>SyntaxKind.FuncKeyword,"if"=>SyntaxKind.IfKeyword,"else"=>SyntaxKind.ElseKeyword,"while"=>SyntaxKind.WhileKeyword,"return"=>SyntaxKind.ReturnKeyword,"true"=>SyntaxKind.TrueKeyword,"false"=>SyntaxKind.FalseKeyword,"nil"=>SyntaxKind.NilKeyword,"struct"=>SyntaxKind.StructKeyword,"class"=>SyntaxKind.ClassKeyword,"init"=>SyntaxKind.InitKeyword,"self"=>SyntaxKind.SelfKeyword,"mutating"=>SyntaxKind.MutatingKeyword,"enum"=>SyntaxKind.EnumKeyword,"case"=>SyntaxKind.CaseKeyword,"switch"=>SyntaxKind.SwitchKeyword,"default"=>SyntaxKind.DefaultKeyword,"throws"=>SyntaxKind.ThrowsKeyword,"throw"=>SyntaxKind.ThrowKeyword,"try"=>SyntaxKind.TryKeyword,"do"=>SyntaxKind.DoKeyword,"catch"=>SyntaxKind.CatchKeyword,"protocol"=>SyntaxKind.ProtocolKeyword,"static"=>SyntaxKind.StaticKeyword,_=>SyntaxKind.IdentifierToken};
 public static int GetUnaryOperatorPrecedence(SyntaxKind k)=>k is SyntaxKind.BangToken or SyntaxKind.PlusToken or SyntaxKind.MinusToken?7:0;
 public static int GetBinaryOperatorPrecedence(SyntaxKind k)=>k switch{SyntaxKind.StarToken or SyntaxKind.SlashToken or SyntaxKind.PercentToken=>6,SyntaxKind.PlusToken or SyntaxKind.MinusToken=>5,SyntaxKind.LessToken or SyntaxKind.LessOrEqualToken or SyntaxKind.GreaterToken or SyntaxKind.GreaterOrEqualToken=>4,SyntaxKind.EqualEqualToken or SyntaxKind.BangEqualToken=>3,SyntaxKind.AmpersandAmpersandToken=>2,SyntaxKind.PipePipeToken=>1,_=>0};
 public static bool IsKeyword(SyntaxKind k)=>k>=SyntaxKind.LetKeyword&&k<=SyntaxKind.StaticKeyword; public static bool IsTrivia(SyntaxKind k)=>k>=SyntaxKind.WhitespaceTrivia&&k<=SyntaxKind.SkippedTextTrivia;
 public static bool CanStartExpression(SyntaxKind k)=>k is SyntaxKind.IdentifierToken or SyntaxKind.IntegerLiteralToken or SyntaxKind.FloatingPointLiteralToken or SyntaxKind.StringLiteralToken or SyntaxKind.TrueKeyword or SyntaxKind.FalseKeyword or SyntaxKind.NilKeyword or SyntaxKind.OpenParenthesisToken or SyntaxKind.SelfKeyword or SyntaxKind.TryKeyword or SyntaxKind.BangToken or SyntaxKind.PlusToken or SyntaxKind.MinusToken;
 public static bool CanStartStatement(SyntaxKind k)=>k is SyntaxKind.OpenBraceToken or SyntaxKind.LetKeyword or SyntaxKind.VarKeyword or SyntaxKind.IfKeyword or SyntaxKind.WhileKeyword or SyntaxKind.ReturnKeyword or SyntaxKind.SwitchKeyword or SyntaxKind.ThrowKeyword or SyntaxKind.DoKeyword || CanStartExpression(k);
}
