using System.Collections.Immutable;
using System.Linq;
using Martin.Compiler.Analysis.Protocols;
using Martin.Compiler.Diagnostics;
using Martin.Compiler.Generics;
using Martin.Compiler.Syntax;
using Martin.Compiler.Text;

namespace Martin.Compiler.Symbols;
public enum SymbolKind { Type, NamedType, Property, Method, Initializer, Function, BuiltInFunction, Parameter, LocalVariable, GlobalVariable, SelfParameter, EnumCase, ProtocolRequirement, TypeParameter }
public abstract class Symbol(string name, ImmutableArray<TextLocation> locations){ public abstract SymbolKind Kind{get;} public string Name{get;}=name; public ImmutableArray<TextLocation> Locations{get;}=locations; public TextLocation? DeclarationLocation=>Locations.IsDefaultOrEmpty?null:Locations[0]; public override string ToString()=>Name; }
public class TypeSymbol : Symbol { protected TypeSymbol(string name, ImmutableArray<TextLocation> locations = default):base(name,locations.IsDefault?[]:locations){ } public override SymbolKind Kind=>SymbolKind.Type; public virtual bool IsValueType => this != String && this != Nil && this != Error; public virtual bool IsReferenceType => this == String; public virtual bool IsOptional => false; public virtual bool IsErrorType => this == Error; public static readonly TypeSymbol Error=new("<error>"); public static readonly TypeSymbol Void=new("Void"); public static readonly TypeSymbol Bool=new("Bool"); public static readonly TypeSymbol Int=new("Int"); public static readonly TypeSymbol Double=new("Double"); public static readonly TypeSymbol String=new("String"); public static readonly TypeSymbol Nil=new("Nil"); public static ImmutableArray<TypeSymbol> BuiltIns=>[Void,Bool,Int,Double,String,Nil]; }
public sealed class OptionalTypeSymbol(TypeSymbol elementType):TypeSymbol(elementType.Name+"?"){ public TypeSymbol ElementType{get;}=elementType; public override bool IsOptional=>true; public override bool IsValueType=>true; public override bool IsReferenceType=>false; }
public abstract class NamedTypeSymbol(string name, bool isStruct, ImmutableArray<TextLocation> locations, ImmutableArray<TypeParameterSymbol> typeParameters = default):TypeSymbol(name,locations){ readonly List<MemberSymbol> _members=[]; public override SymbolKind Kind=>SymbolKind.NamedType; public bool IsStruct{get;}=isStruct; public ImmutableArray<TypeParameterSymbol> TypeParameters{get;}=typeParameters.IsDefault?[]:typeParameters; public bool IsGeneric=>TypeParameters.Length>0; public bool IsClass=>!IsStruct; public override bool IsValueType=>IsStruct; public override bool IsReferenceType=>IsClass; public ImmutableArray<MemberSymbol> Members=>_members.ToImmutableArray(); public ImmutableArray<PropertySymbol> Properties=>_members.OfType<PropertySymbol>().ToImmutableArray(); public ImmutableArray<MethodSymbol> Methods=>_members.OfType<MethodSymbol>().ToImmutableArray(); public ImmutableArray<InitializerSymbol> Initializers=>_members.OfType<InitializerSymbol>().ToImmutableArray(); public ImmutableArray<EnumCaseSymbol> Cases=>_members.OfType<EnumCaseSymbol>().ToImmutableArray(); public virtual bool IsEnum=>false; public void AddMember(MemberSymbol m)=>_members.Add(m); }
public sealed class StructTypeSymbol(string name, ImmutableArray<TextLocation> locations, ImmutableArray<TypeParameterSymbol> typeParameters = default):NamedTypeSymbol(name,true,locations,typeParameters);
public sealed class ClassTypeSymbol(string name, ImmutableArray<TextLocation> locations, ImmutableArray<TypeParameterSymbol> typeParameters = default):NamedTypeSymbol(name,false,locations,typeParameters);
public sealed class EnumTypeSymbol(string name, ImmutableArray<TextLocation> locations, ImmutableArray<TypeParameterSymbol> typeParameters = default):NamedTypeSymbol(name,true,locations,typeParameters){ public override bool IsEnum=>true; }
public sealed class ProtocolTypeSymbol(string name, ImmutableArray<TextLocation> locations):NamedTypeSymbol(name,false,locations){ public override bool IsValueType=>false; public override bool IsReferenceType=>false; public ImmutableArray<ProtocolRequirementSymbol> Requirements=>Members.OfType<ProtocolRequirementSymbol>().ToImmutableArray(); }
public sealed class TypeParameterSymbol(string name,int ordinal,Symbol containingSymbol,ImmutableArray<TextLocation> locations):TypeSymbol(name,locations){ public override SymbolKind Kind=>SymbolKind.TypeParameter; public int Ordinal{get;}=ordinal; public TypeIdentity Identity=>TypeIdentity.Create(this); public Symbol ContainingSymbol{get; private set;}=containingSymbol; public void SetContainingSymbol(Symbol containingSymbol)=>ContainingSymbol=containingSymbol; public ImmutableArray<GenericConstraint> Constraints{get; private set;}=[]; public void SetConstraints(ImmutableArray<GenericConstraint> constraints)=>Constraints=constraints; }
public sealed class ConstructedTypeSymbol(NamedTypeSymbol genericDefinition, ImmutableArray<TypeSymbol> typeArguments, ImmutableArray<MemberSymbol> members):TypeSymbol(genericDefinition.Name+"<"+string.Join(", ", typeArguments.Select(t=>t.Name))+">",genericDefinition.Locations){ ImmutableArray<MemberSymbol> _members=members; public NamedTypeSymbol GenericDefinition{get;}=genericDefinition; public TypeIdentity Identity=>TypeIdentity.Create(this); public ImmutableArray<TypeSymbol> TypeArguments{get;}=typeArguments; public ImmutableArray<MemberSymbol> Members=>_members; internal void CompleteMembers(ImmutableArray<MemberSymbol> members)=>_members=members; public ImmutableArray<PropertySymbol> Properties=>Members.OfType<PropertySymbol>().ToImmutableArray(); public ImmutableArray<MethodSymbol> Methods=>Members.OfType<MethodSymbol>().ToImmutableArray(); public ImmutableArray<InitializerSymbol> Initializers=>Members.OfType<InitializerSymbol>().ToImmutableArray(); public ImmutableArray<EnumCaseSymbol> Cases=>Members.OfType<EnumCaseSymbol>().ToImmutableArray(); public bool IsEnum=>GenericDefinition.IsEnum; public override bool IsValueType=>GenericDefinition.IsValueType; public override bool IsReferenceType=>GenericDefinition.IsReferenceType; }
public abstract record GenericConstraint;
public sealed record ProtocolConstraint(ProtocolTypeSymbol Protocol):GenericConstraint;
public abstract class MemberSymbol(string name, TypeSymbol containingType, bool isStatic, ImmutableArray<TextLocation> locations):Symbol(name,locations){ public TypeSymbol ContainingType{get;}=containingType; public bool IsStatic{get;}=isStatic; }
public sealed class PropertySymbol(string name, TypeSymbol containingType, TypeSymbol type, bool isReadOnly, ExpressionSyntax? defaultValueSyntax, ImmutableArray<TextLocation> locations, PropertySymbol? originalDefinition=null):MemberSymbol(name,containingType,false,locations){ public override SymbolKind Kind=>SymbolKind.Property; public TypeSymbol Type{get;}=type; public bool IsReadOnly{get;}=isReadOnly; public bool IsStored=>true; public ExpressionSyntax? DefaultValueSyntax{get;}=defaultValueSyntax; public PropertySymbol OriginalDefinition=>originalDefinition?.OriginalDefinition??this; }
public sealed class MethodSymbol(string name, TypeSymbol containingType, ImmutableArray<ParameterSymbol> parameters, TypeSymbol returnType, SyntaxNode declaration, bool isMutating, ImmutableArray<TextLocation> locations, bool isThrowing=false, TypeSymbol? errorType=null, ImmutableArray<TypeParameterSymbol> typeParameters=default, ImmutableArray<GenericConstraint> genericRequirements=default, MethodSymbol? originalDefinition=null):MemberSymbol(name,containingType,false,locations){ public override SymbolKind Kind=>SymbolKind.Method; public ImmutableArray<ParameterSymbol> Parameters{get;}=parameters; public TypeSymbol ReturnType{get;}=returnType; public SyntaxNode Declaration{get;}=declaration; public bool IsMutating{get;}=isMutating; public bool IsThrowing{get;}=isThrowing; public TypeSymbol? ErrorType{get;}=errorType; public ImmutableArray<TypeParameterSymbol> TypeParameters{get;}=typeParameters.IsDefault?[]:typeParameters; public ImmutableArray<GenericConstraint> GenericRequirements{get;}=genericRequirements.IsDefault?[]:genericRequirements; public MethodSymbol OriginalDefinition=>originalDefinition?.OriginalDefinition??this; }
public sealed class EnumCaseSymbol(string name, TypeSymbol containingType, ImmutableArray<ParameterSymbol> associatedValues, ImmutableArray<TextLocation> locations, EnumCaseSymbol? originalDefinition=null):MemberSymbol(name,containingType,true,locations){ public override SymbolKind Kind=>SymbolKind.EnumCase; public ImmutableArray<ParameterSymbol> AssociatedValues{get;}=associatedValues; public bool HasAssociatedValues=>!AssociatedValues.IsDefaultOrEmpty; public EnumCaseSymbol OriginalDefinition=>originalDefinition?.OriginalDefinition??this; }
public abstract class ProtocolRequirementSymbol(string name, ProtocolTypeSymbol containingProtocol, bool isStatic, string stableId, ImmutableArray<TextLocation> locations):MemberSymbol(name,containingProtocol,isStatic,locations){ public override SymbolKind Kind=>SymbolKind.ProtocolRequirement; public ProtocolTypeSymbol ContainingProtocol{get;}=containingProtocol; public string StableId{get;}=stableId; }
public sealed class ProtocolMethodRequirementSymbol(string name, ProtocolTypeSymbol containingProtocol, ImmutableArray<ParameterSymbol> parameters, TypeSymbol returnType, bool isMutating, bool isThrowing, TypeSymbol? errorType, ImmutableArray<TypeParameterSymbol> typeParameters, ImmutableArray<GenericConstraint> genericRequirements, string stableId, ImmutableArray<TextLocation> locations, bool isStatic=false):ProtocolRequirementSymbol(name,containingProtocol,isStatic,stableId,locations){ public ImmutableArray<ParameterSymbol> Parameters{get;}=parameters; public TypeSymbol ReturnType{get;}=returnType; public bool IsMutating{get;}=isMutating; public bool IsThrowing{get;}=isThrowing; public TypeSymbol? ErrorType{get;}=errorType; public ImmutableArray<TypeParameterSymbol> TypeParameters{get;}=typeParameters; public ImmutableArray<GenericConstraint> GenericRequirements{get;}=genericRequirements; }
public sealed class ProtocolPropertyRequirementSymbol(string name, ProtocolTypeSymbol containingProtocol, TypeSymbol propertyType, bool requiresGetter, bool requiresSetter, string stableId, ImmutableArray<TextLocation> locations, bool isStatic=false):ProtocolRequirementSymbol(name,containingProtocol,isStatic,stableId,locations){ public TypeSymbol PropertyType{get;}=propertyType; public TypeSymbol Type=>PropertyType; public bool RequiresGetter{get;}=requiresGetter; public bool RequiresSetter{get;}=requiresSetter; }
public sealed record ProtocolConformance(NamedTypeSymbol Type, ProtocolTypeSymbol Protocol, ImmutableDictionary<ProtocolRequirementSymbol, MemberSymbol> Witnesses, ImmutableDictionary<MemberSymbol, ImmutableArray<ProtocolRequirementSymbol>> RequirementsByWitness);
public sealed record ProtocolConformanceAttempt(
    NamedTypeSymbol Type,
    ProtocolTypeSymbol Protocol,
    TextLocation DeclarationLocation,
    ImmutableDictionary<ProtocolRequirementSymbol, ProtocolRequirementMatch> Mismatches,
    ImmutableDictionary<ProtocolRequirementSymbol, MemberSymbol> Witnesses,
    ImmutableDictionary<MemberSymbol, ImmutableArray<ProtocolRequirementSymbol>> RequirementsByWitness)
{
    public bool IsValid => Mismatches.IsEmpty;
    public ProtocolConformance? Validated => IsValid ? new(Type, Protocol, Witnesses, RequirementsByWitness) : null;
}
public sealed class InitializerSymbol(TypeSymbol containingType, ImmutableArray<ParameterSymbol> parameters, SyntaxNode? declaration, bool isSynthesized, ImmutableArray<TextLocation> locations, bool isThrowing=false, TypeSymbol? errorType=null, InitializerSymbol? originalDefinition=null):MemberSymbol("init",containingType,false,locations){ public override SymbolKind Kind=>SymbolKind.Initializer; public ImmutableArray<ParameterSymbol> Parameters{get;}=parameters; public SyntaxNode? Declaration{get;}=declaration; public bool IsSynthesized{get;}=isSynthesized; public bool IsThrowing{get;}=isThrowing; public TypeSymbol? ErrorType{get;}=errorType; public InitializerSymbol OriginalDefinition=>originalDefinition?.OriginalDefinition??this; }
public abstract class VariableSymbol(string name,bool isReadOnly,TypeSymbol type,ImmutableArray<TextLocation> locations):Symbol(name,locations){ public bool IsReadOnly{get;}=isReadOnly; public TypeSymbol Type{get;}=type; }
public sealed class SelfParameterSymbol(NamedTypeSymbol containingType, bool isMutable, ImmutableArray<TextLocation> locations):VariableSymbol("self",!isMutable,containingType,locations){ public override SymbolKind Kind=>SymbolKind.SelfParameter; public NamedTypeSymbol ContainingType{get;}=containingType; public bool IsMutable{get;}=isMutable; }
public class LocalVariableSymbol(string name,bool isReadOnly,TypeSymbol type,ImmutableArray<TextLocation> locations):VariableSymbol(name,isReadOnly,type,locations){ public override SymbolKind Kind=>SymbolKind.LocalVariable; }
public sealed class CompilerGeneratedLocalVariableSymbol(string name,TypeSymbol type,TextLocation? originLocation=null):LocalVariableSymbol(name,true,type,originLocation.HasValue ? [originLocation.Value] : []){ public TextLocation? OriginLocation{get;}=originLocation; }
public sealed class GlobalVariableSymbol(string name,bool isReadOnly,TypeSymbol type,ImmutableArray<TextLocation> locations):VariableSymbol(name,isReadOnly,type,locations){ public override SymbolKind Kind=>SymbolKind.GlobalVariable; }
public sealed class ParameterSymbol(string name,string? label,int ordinal,TypeSymbol type,ImmutableArray<TextLocation> locations, bool isVariadic=false, bool hasDefaultValue=false):VariableSymbol(name,true,type,locations){ public override SymbolKind Kind=>SymbolKind.Parameter; public string? Label{get;}=label; public string LocalName=>Name; public int Ordinal{get;}=ordinal; public bool IsVariadic{get;}=isVariadic; public bool HasDefaultValue{get;}=hasDefaultValue; }
public sealed class FunctionSymbol(string name, ImmutableArray<ParameterSymbol> parameters, TypeSymbol returnType, SyntaxNode? declaration, bool isBuiltIn, ImmutableArray<TextLocation> locations, ImmutableArray<TypeParameterSymbol> typeParameters = default, bool isThrowing=false, TypeSymbol? errorType=null, FunctionSymbol? originalDefinition=null):Symbol(name,locations){ public override SymbolKind Kind=>IsBuiltIn?SymbolKind.BuiltInFunction:SymbolKind.Function; public ImmutableArray<ParameterSymbol> Parameters{get;}=parameters; public TypeSymbol ReturnType{get;}=returnType; public SyntaxNode? Declaration{get;}=declaration; public bool IsBuiltIn{get;}=isBuiltIn; public ImmutableArray<TypeParameterSymbol> TypeParameters{get;}=typeParameters.IsDefault?[]:typeParameters; public bool IsGeneric=>TypeParameters.Length>0; public bool IsThrowing{get;}=isThrowing; public TypeSymbol? ErrorType{get;}=errorType; public FunctionSymbol OriginalDefinition=>originalDefinition?.OriginalDefinition??this; }
